# Generated by Django 3.0.4 on 2020-04-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
